branch-defaults:
  develop:
    environment: desabono
    group_suffix: null
global:
  application_name: desabono
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
