# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0001_initial'),
        ('divida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.CharField(max_length=8000, null=True)),
                ('data_add', models.DateField(null=True)),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto.credor')),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divida.divida')),
            ],
        ),
    ]
