# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='coment',
            field=models.CharField(max_length=8000, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='citado',
            field=models.CharField(max_length=8000, null=True, verbose_name='Citado'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='credor_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto.credor', verbose_name='CNPJ do credor'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='descricao',
            field=models.CharField(max_length=8000, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='termos',
            field=models.BooleanField(default=False, verbose_name='Termos de uso'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='tipo_divida',
            field=models.CharField(choices=[('DV', 'Duplicidade'), ('CD', 'Cheque devolvido'), ('SD', 'Saldo devedor'), ('JP', 'Juros nao pagos'), ('OT', 'Outro')], default='OT', max_length=2, null=True, verbose_name='Tipo de d\xedvida'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='valor',
            field=models.FloatField(null=True, verbose_name='Valor da divida'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='vencimento',
            field=models.CharField(max_length=20, null=True, verbose_name='Vencimento'),
        ),
    ]
