# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0003_auto_20160505_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='ident_devedor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divida',
            name='nome_devedor',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
