# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0004_auto_20160506_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='credor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='divida',
            name='credor_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CNPJ do credor'),
        ),
    ]
