# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0005_auto_20160516_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='foi_paga',
            field=models.BooleanField(default=False, verbose_name='Foi paga'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='ident_devedor',
            field=models.CharField(max_length=100, null=True, verbose_name='cnpj do devedor'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='d\xedvida ativa'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='nome_devedor',
            field=models.CharField(max_length=2000, null=True, verbose_name='nome do devedor'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='tipo_divida',
            field=models.CharField(choices=[('DV', 'Duplicidade'), ('CD', 'Cheque devolvido'), ('SD', 'Saldo devedor'), ('JP', 'Juros n\xe3o pagos'), ('OT', 'Outro')], default='OT', max_length=2, null=True, verbose_name='Tipo de d\xedvida'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='vencimento',
            field=models.CharField(max_length=20, null=True, verbose_name='Vencimento da d\xedvida'),
        ),
    ]
