# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0006_auto_20160517_1557'),
        ('divida', '0005_auto_20160514_1418'),
    ]

    operations = [
    ]
