# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0008_auto_20160518_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='vencimento',
            field=models.DateField(null=True, verbose_name='Vencimento da d\xedvida'),
        ),
    ]
