# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0009_auto_20160519_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divida',
            name='citado',
        ),
        migrations.AddField(
            model_name='divida',
            name='citados',
            field=models.CharField(max_length=8000, null=True, verbose_name='Citados'),
        ),
    ]
