# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0010_auto_20160519_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='tipo_divida',
            field=models.CharField(choices=[('DV', 'Duplicata'), ('CD', 'Cheque devolvido'), ('SD', 'Saldo devedor'), ('JP', 'Juros n\xe3o pagos'), ('OT', 'Outro')], default='OT', max_length=2, null=True, verbose_name='Tipo de d\xedvida'),
        ),
    ]
