# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0010_auto_20160711_1447'),
        ('divida', '0012_divida_ident_devedor_cleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='credor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posto.credor', verbose_name='Credor'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='tipo_divida',
            field=models.CharField(choices=[('DV', 'Duplicata'), ('CD', 'Cheque devolvido'), ('SD', 'Saldo devedor'), ('JP', 'Juros n\xe3o pagos'), ('OT', 'Outro')], default='DV', max_length=2, null=True, verbose_name='Tipo de d\xedvida'),
        ),
    ]
