# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0010_auto_20160711_1447'),
        ('divida', '0013_auto_20160711_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, null=True)),
                ('resultado', models.CharField(max_length=8000, null=True)),
                ('tempo', models.FloatField(null=True)),
                ('insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto.credor')),
            ],
        ),
        migrations.CreateModel(
            name='DividaDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, null=True)),
                ('insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('divida_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divida.divida')),
            ],
        ),
    ]
