# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divida', '0014_consultalog_dividadados'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultalog',
            name='termo_buscado',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
