# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('cnpj', models.CharField(max_length=12)),
                ('endereco', models.CharField(blank=True, max_length=8000)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(max_length=255)),
                ('ip_user', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=8000)),
            ],
        ),
    ]
