# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='cnpj',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='credor',
            name='descricao',
            field=models.CharField(max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='credor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='credor',
            name='endereco',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='credor',
            name='ip_user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credor',
            name='nome',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='credor',
            name='tipo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
