# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0002_auto_20160506_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='endereco',
            field=models.CharField(blank=True, max_length=8000, null=True, verbose_name='Endere\xe7o'),
        ),
        migrations.AlterField(
            model_name='credor',
            name='tipo',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo da d\xedvida'),
        ),
    ]
