# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0003_auto_20160427_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='cnpj',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
