# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0005_credor_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='cnpj',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
