# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0006_auto_20160520_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='credor',
            name='tipo_empresa',
            field=models.CharField(choices=[('FAC', 'Factoring'), ('FDC', 'FIDC'), ('SEC', 'Securizadora'), ('OTR', 'Outro')], default='OTR', max_length=3, null=True, verbose_name='Tipo de empresa'),
        ),
    ]
