# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0007_credor_tipo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='credor',
            name='cargo',
            field=models.CharField(max_length=100, null=True, verbose_name='Cargo na empresa'),
        ),
    ]
