# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0008_credor_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='credor',
            name='site',
            field=models.CharField(max_length=1000, null=True, verbose_name='Site da empresa'),
        ),
    ]
